---

- name: Remove older versions of Docker
  apt:
    pkg: "{{ docker_packages_to_remove }}"
    state: absent

- name: Install packages needed by Docker
  apt:
    pkg: "{{ required_packages_to_install_docker }}"
    state: present

- name: Install docker from pip
  pip:
    executable: pip3
    name: docker

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: Update repositories cache and install Docker Engine and containerd
  apt:
    update_cache: yes
    pkg: "{{ docker_packages_to_install }}"

- name: Verify that docker engine is installed correctly
  community.general.docker_container:
    container_default_behavior: compatibility
    name: helloworld
    image: hello-world
    auto_remove: yes

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version  }}/docker-compose-Linux-{{ docker_compose_arch  }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
