---
# tasks file for debian_setup

- name: Update cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    state: present
    pkg: "{{ needed_packages }}"

- name: Set up ufw
  include_tasks: ufw.yml

- name: Create the user
  include_tasks: user.yml

- name: Change SSH daemon's configuration
  include_tasks: sshd.yml

- name: Install Docker and Docker Compose
  vars:
    docker_users:
      - "{{ username }}"
  include_role:
    name: geerlingguy.docker
  when: install_docker | bool
