---

- name: Set PasswordAuthentication to no
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^(# *)?PasswordAuthentication yes
    line: PasswordAuthentication no

- name: Set PermitRootLogin to no
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^(# *)?PermitRootLogin
    line: PermitRootLogin no

- name: Restart SSH daemon
  systemd:
    name: sshd.service
    state: restarted
    daemon_reload: yes
