---

- name: Create the user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/bash
    append: yes
    groups: sudo

- name: Add authorized key
  authorized_key:
    state: present
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_public_key_path) }}"
